USE meupatrimonio
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE SEQUENCE SEQ_PATRIMONIO_TOMBO START WITH 1;

CREATE TABLE meupatrimonio.MARCA(
	Id int NOT NULL IDENTITY(1,1),
	Nome varchar(30) NOT NULL,
	
	CONSTRAINT PK_MARCA_ID PRIMARY KEY NONCLUSTERED (ID)
) ON [PRIMARY]
GO

CREATE TABLE meupatrimonio.MODELO(
	Id int NOT NULL IDENTITY(1,1),
	Marca int NOT NULL,
	Nome varchar(30) NOT NULL,
	
	CONSTRAINT PK_MODELO_ID PRIMARY KEY NONCLUSTERED (ID),
	CONSTRAINT FK_MODELO_MARCA_ID FOREIGN KEY (MARCA) REFERENCES meupatrimonio.MARCA(ID)
) ON [PRIMARY]
GO

CREATE TABLE meupatrimonio.PATRIMONIO(
	Id int NOT NULL IDENTITY(1,1),
	Marca int NOT NULL,
	Modelo int NOT NULL,
	Descricao varchar(30),
	Tombo int NOT NULL DEFAULT NEXT VALUE FOR SEQ_PATRIMONIO_TOMBO
	
	CONSTRAINT PK_PATRIMONIO_ID PRIMARY KEY NONCLUSTERED (ID),
	CONSTRAINT FK_PATRIMONIO_MARCA_ID FOREIGN KEY (MARCA) REFERENCES meupatrimonio.MARCA(ID),
	CONSTRAINT FK_PATRIMONIO_MODELO_ID FOREIGN KEY (MODELO) REFERENCES meupatrimonio.MODELO(ID)
) ON [PRIMARY]
GO


